version: '3'

services:
  front:
    build: Front
    container_name: front
    ports:
    - "8888:80"
    networks:
    - backend

  server-soap:
    image: server-soap
    container_name: server-soap
    build: ServerSOAP
    networks:
    - backend
    ports:
    - "8001:8001"

  server-rest:
    image: server-rest
    container_name: server-rest
    build: ServerRest
    ports:
    - "8085:80"
    networks:
    - backend

  postgres:
    image: postgres
    container_name: postgres-kc
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - security


  keycloak:
    image: jboss/keycloak:4.8.3.Final
    container_name: auth
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
    - 8080:8080
    depends_on:
    - postgres
    networks:
    - backend
    - security

networks:
  backend:
  security:

volumes:
  postgres_data:
    driver: local