
package infres.ws.soap.implementations;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import infres.ws.soap.contracts.ObjectFactory;
import infres.ws.soap.contracts.Reservation;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IReservations", targetNamespace = "http://contracts.soap.ws.infres/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IReservations {


    /**
     * 
     * @param id
     * @return
     *     returns infres.ws.soap.contracts.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.contracts.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.contracts.FindResponse")
    @Action(input = "http://contracts.soap.ws.infres/IReservations/findRequest", output = "http://contracts.soap.ws.infres/IReservations/findResponse")
    public Reservation find(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<infres.ws.soap.contracts.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.contracts.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.contracts.FindAllResponse")
    @Action(input = "http://contracts.soap.ws.infres/IReservations/findAllRequest", output = "http://contracts.soap.ws.infres/IReservations/findAllResponse")
    public List<Reservation> findAll();

}
