
package infres.ws.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IReservations", targetNamespace = "http://contracts.soap.ws.infres/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IReservations {


    /**
     * 
     * @param id
     * @return
     *     returns infres.ws.soap.server.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.server.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.server.FindResponse")
    @Action(input = "http://contracts.soap.ws.infres/IReservations/findRequest", output = "http://contracts.soap.ws.infres/IReservations/findResponse")
    public Reservation find(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<infres.ws.soap.server.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.server.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://contracts.soap.ws.infres/", className = "infres.ws.soap.server.FindAllResponse")
    @Action(input = "http://contracts.soap.ws.infres/IReservations/findAllRequest", output = "http://contracts.soap.ws.infres/IReservations/findAllResponse")
    public List<Reservation> findAll();

}
